version: '3.8'

services:
  db_fastapi:
    image: postgres:15
    container_name: postgres_fastapi
    environment:
      POSTGRES_DB: ${DB_NAME_FASTAPI}
      POSTGRES_USER: ${DB_USER_FASTAPI}
      POSTGRES_PASSWORD: ${DB_PASSWORD_FASTAPI}
    volumes:
      - postgres_data_fastapi:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_fastapi
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      DATABASE_URL: "postgresql+asyncpg://${DB_USER_FASTAPI}:${DB_PASSWORD_FASTAPI}@db_fastapi/${DB_NAME_FASTAPI}"
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
    ports:
      - "8000:8000"
    depends_on:
      - db_fastapi
    volumes:
      - ./documents:/app/documents
    networks:
      - app-network

  celery:
    build: .
    command: celery -A src.core.celery_worker.celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
      - db_fastapi
    environment:
      DATABASE_URL: "postgresql+asyncpg://${DB_USER_FASTAPI}:${DB_PASSWORD_FASTAPI}@db_fastapi/${DB_NAME_FASTAPI}"
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
    volumes:
      - ./documents:/app/documents
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  postgres_data_fastapi:
