version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql+asyncpg://${DB_USER}:${DB_PASS}@db/${DB_NAME}"
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./documents:/app/documents

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  celery:
    build: .
    command: celery -A src.core.celery_worker.celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://${DB_USER}:${DB_PASS}@db/${DB_NAME}"
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
    volumes:
      - ./documents:/app/documents

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  pgadmin_data:
